### ISSUE TITLE
add drop-down menu for specific date requests

### ISSUE THREAD

**Issue by moritzkreinsen** [base-camp-luftdaten/frontend#6]
Tom suggested at the last session to add a kind of drop-down menu, which allows specific dates to be set, e.g. yesterday 5 pm or (for the forecast) coming Saturday 6 am.

**Comment by lionralfs** [comment]
In order to do that, we need a way to request the data for a specific time span (for example: -48hours ago to -24hours ago). The [current API](https://github.com/opendata-stuttgart/meta/wiki/APIs#accessing-the-api-data) only gives us the last 24hours. We might have to use our own API to do that.

Maybe keep this for later.
